[versions]
gradle = "8.1.1"
javaToolchain = "11"
android-buildToolsVersion = "33.0.2"
android-ndkVersion = "25.2.9519653"
android-compileSdk = "33"
android-compileSdkExtension = "5"
android-minSdk = "21"
android-targetSdk = "33"
