[versions]
javaToolchain = "17"
android-buildToolsVersion = "35.0.0"
android-ndkVersion = "27.1.12297006"
android-compileSdk = "35"
android-compileSdkExtension = "-"
android-minSdk = "21"
android-targetSdk = "34"
