[versions]
javaToolchain = "21"
android-buildToolsVersion = "36.0.0"
android-ndkVersion = "28.1.13356709"
android-compileSdk = "36"
android-compileSdkExtension = "-"
android-minSdk = "21"
android-targetSdk = "34"
