[versions]
javaToolchain = "17"
android-buildToolsVersion = "35.0.0"
android-ndkVersion = "26.2.11394342"
android-compileSdk = "34"
android-compileSdkExtension = "-"
android-minSdk = "21"
android-targetSdk = "34"
