[versions]
gradle = "8.2.1"
javaToolchain = "17"
android-buildToolsVersion = "34.0.0"
android-ndkVersion = "25.2.9519653"
android-compileSdk = "34"
android-compileSdkExtension = "-"
android-minSdk = "21"
android-targetSdk = "33"
