[versions]
gradle = "8.6"
javaToolchain = "17"
android-buildToolsVersion = "34.0.0"
android-ndkVersion = "26.1.10909125"
android-compileSdk = "34"
android-compileSdkExtension = "-"
android-minSdk = "21"
android-targetSdk = "34"
