[versions]
# General components
kotlin = "1.8.10"
gradle = "7.6"
# Plugins and tools, mobile-services independent
kspPlugin = "1.8.10-1.0.9"
androidPlugin = "7.4.1"
versionsPlugin = "0.45.0"
spotlessPlugin = "6.14.1"
ktlintTool = "0.46.1"
anvilPlugin = "2.4.4"
grgitPlugin = "5.0.0"
mavenPublishPlugin = "0.24.0"
# KotlinX libraries
kotlinx-coroutines = "1.6.4"
# AndroidX libraries
androidx-activity = "1.6.1"
androidx-annotation-main = "1.5.0"
androidx-appcompat = "1.6.1"
androidx-constraintlayout-main = "2.2.0-alpha07"
androidx-core-runtime = "1.9.0"
androidx-fragment = "1.5.5"
androidx-lifecycle = "2.5.1"
androidx-savedstate = "1.2.0"
androidx-work = "2.8.0"
# Material Design Components and UI
material-native = "1.8.0"
#
timber = "5.0.1"
dagger = "2.44.2"
#
kotlinpoet = "1.12.0"
auto-service = "1.0.1"
auto-service-ksp = "1.0.0"
# Testing instruments
junit = "4.13.2"
androidx-test-core = "1.5.0"
androidx-test-monitor = "1.6.1"
androidx-test-orchestrator = "1.4.2"
androidx-test-rules = "1.5.0"
androidx-test-runner = "1.5.2"
androidx-test-ext-junit = "1.1.5"
androidx-test-espresso = "3.5.1"

[libraries]
#
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidPlugin" }
anvil-gradlePlugin = { group = "com.squareup.anvil", name = "gradle-plugin", version.ref = "anvilPlugin" }
spotless-gradlePlugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotlessPlugin" }
mavenPublish-gradlePlugin = { group = "com.vanniktech.maven.publish", name = "com.vanniktech.maven.publish.gradle.plugin", version.ref = "mavenPublishPlugin" }
#
kotlin-stdlib-core = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
#
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
#
androidx-activity-runtime = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-runtimeKtx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-annotation-main = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation-main" }
androidx-appcompat-runtime = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout-main = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout-main" }
androidx-core-runtime = { module = "androidx.core:core", version.ref = "androidx-core-runtime" }
androidx-core-runtimeKtx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-runtime" }
androidx-fragment-runtime = { module = "androidx.fragment:fragment", version.ref = "androidx-fragment" }
androidx-fragment-runtimeKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModelSavedState = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-savedstate-runtime = { module = "androidx.savedstate:savedstate", version.ref = "androidx-savedstate" }
androidx-savedstate-runtimeKtx = { module = "androidx.savedstate:savedstate-ktx", version.ref = "androidx-savedstate" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "androidx-work" }
androidx-work-runtimeKtx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
# Material design components
material-native = { module = "com.google.android.material:material", version.ref = "material-native" }
#
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-runtime = { module = "com.google.dagger:dagger", version.ref = "dagger" }
#
kotlinpoet-core = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
kotlinpoet-kotlinx-metadata = { module = "com.squareup:kotlinpoet-metadata", version.ref = "kotlinpoet" }
anvil-annotations = { module = "com.squareup.anvil:annotations", version.ref = "anvilPlugin" }
anvil-compiler-api = { module = "com.squareup.anvil:compiler-api", version.ref = "anvilPlugin" }
anvil-compiler-core = { module = "com.squareup.anvil:compiler", version.ref = "anvilPlugin" }
anvil-compiler-utils = { module = "com.squareup.anvil:compiler-utils", version.ref = "anvilPlugin" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service" }
auto-service-processor-kapt = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }
auto-service-processor-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "auto-service-ksp" }
# Testing instruments
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-jdk = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-coreKtx = { module = "androidx.test:core-ktx", version.ref = "androidx-test-core" }
androidx-test-monitor = { module = "androidx.test:monitor", version.ref = "androidx-test-monitor" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx-test-orchestrator" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-ext-junitKtx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext-junit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }

[bundles]
kotlin-stdlib = ["kotlin-stdlib-core", "kotlin-stdlib-jdk7", "kotlin-stdlib-jdk8"]

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotlessPlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
anvil = { id = "com.squareup.anvil", version.ref = "anvilPlugin" }
android-application = { id = "com.android.application", version.ref = "androidPlugin" }
android-library = { id = "com.android.library", version.ref = "androidPlugin" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgitPlugin" }
grgitService = { id = "org.ajoberstar.grgit.service", version.ref = "grgitPlugin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublishPlugin" }
