/*
 * Copyright 2022 Ihor Kushnirenko
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.steinerok.sealant.viewmodel

import androidx.annotation.Keep
import androidx.lifecycle.ViewModel
import dagger.MapKey
import dev.steinerok.sealant.core.internal.InternalSealantApi
import javax.inject.Qualifier
import kotlin.reflect.KClass

/**
 * Contributes a [ViewModel] to Sealant's generated ViewModel graph.
 *
 * The annotated class is registered for the supplied scope and can then be created through
 * [SealantViewModelFactoryCreator]. Both regular `@Inject` and `@AssistedInject` constructors
 * are supported.
 */
@Keep
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
public annotation class ContributesViewModel(

    /** The scope from which to pull the annotated class's dependencies. */
    val scope: KClass<out Any>,

    /**
     * Returns a factory class that can be used to create this ViewModel with assisted injection.
     * The default value `Nothing::class` denotes that no factory is specified and the ViewModel
     * is not assisted injected.
     */
    val assistedFactory: KClass<*> = Nothing::class,
)

/**
 * Contributes a Dagger module or binding type to the generated `ViewModel_<Scope>` graph.
 *
 * This is typically used for dependencies that should only exist while a Sealant-created
 * ViewModel subcomponent is alive.
 */
@Keep
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
public annotation class ContributesToViewModel(

    /** The scope from which to pull the annotated class's dependencies. */
    val scope: KClass<out Any>,
)

/**
 * Annotation to be applied to a getter or setter function that is stored in the binary output.
 * A [ViewModelKey] with [KClass] object will be the key in a Map generated by Dagger.
 * The value will be the [ViewModel] to be retrieved based on the key.
 */
@InternalSealantApi
@MapKey
@Target(
    AnnotationTarget.CLASS,
    AnnotationTarget.FUNCTION,
    AnnotationTarget.PROPERTY_GETTER,
    AnnotationTarget.PROPERTY_SETTER
)
@Retention(AnnotationRetention.RUNTIME)
public annotation class ViewModelKey(

    /**
     * The [ViewModel] class used as a key.
     *
     * @return the class.
     */
    val value: KClass<out ViewModel>,
)

/** Qualifier for the multibinding map of directly creatable ViewModel providers. */
@InternalSealantApi
@Qualifier
@Retention(AnnotationRetention.RUNTIME)
@Target(
    AnnotationTarget.PROPERTY_GETTER,
    AnnotationTarget.FIELD,
    AnnotationTarget.FUNCTION,
    AnnotationTarget.VALUE_PARAMETER
)
public annotation class SealantViewModelMap

/**
 * Internal qualifier for the multibinding map of assisted factories for @AssistedInject-annotated
 * ViewModels used by the [SealantViewModelFactory].
 */
@InternalSealantApi
@Qualifier
@Retention(AnnotationRetention.RUNTIME)
@Target(
    AnnotationTarget.PROPERTY_GETTER,
    AnnotationTarget.FIELD,
    AnnotationTarget.FUNCTION,
    AnnotationTarget.VALUE_PARAMETER
)
public annotation class SealantViewModelAssistedMap


/**
 * Namespace for internal qualifiers used by Sealant's generated ViewModel integration code.
 */
@InternalSealantApi
public interface SealantViewModelSupport {

    /** Qualifies the set of ViewModel classes supported by a parent scope. */
    @Qualifier
    @Retention(AnnotationRetention.RUNTIME)
    @Target(
        AnnotationTarget.PROPERTY_GETTER,
        AnnotationTarget.FIELD,
        AnnotationTarget.VALUE_PARAMETER,
        AnnotationTarget.FUNCTION
    )
    public annotation class KeySet

    /** Qualifies the map of scope name to generated ViewModel subcomponent factory. */
    @Qualifier
    @Retention(AnnotationRetention.RUNTIME)
    @Target(
        AnnotationTarget.PROPERTY_GETTER,
        AnnotationTarget.FIELD,
        AnnotationTarget.VALUE_PARAMETER,
        AnnotationTarget.FUNCTION
    )
    public annotation class SubcomponentMap
}
