package dev.steinerok.sealant

import com.android.build.api.dsl.ApplicationExtension
import com.android.build.api.dsl.CommonExtension
import com.android.build.api.dsl.DynamicFeatureExtension
import com.android.build.api.dsl.LibraryExtension
import com.android.build.api.dsl.TestExtension
import com.android.build.api.variant.AndroidComponentsExtension
import com.android.build.api.variant.ApplicationAndroidComponentsExtension
import com.android.build.api.variant.DynamicFeatureAndroidComponentsExtension
import com.android.build.api.variant.KotlinMultiplatformAndroidComponentsExtension
import com.android.build.api.variant.LibraryAndroidComponentsExtension
import com.android.build.api.variant.TestAndroidComponentsExtension
import org.gradle.accessors.dm.LibrariesForConfiguration
import org.gradle.accessors.dm.LibrariesForConfiguration.VersionAccessors
import org.gradle.accessors.dm.LibrariesForLibs
import org.gradle.api.Project
import org.gradle.api.artifacts.VersionCatalog
import org.gradle.api.artifacts.VersionCatalogsExtension
import org.gradle.api.artifacts.dsl.DependencyHandler
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.getByType
import org.gradle.kotlin.dsl.the
import org.jetbrains.kotlin.gradle.dsl.KotlinAndroidExtension
import org.jetbrains.kotlin.gradle.dsl.KotlinBaseExtension
import org.jetbrains.kotlin.gradle.dsl.KotlinJvmExtension
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension

//region Version Catalogs & Accessors

/**
 * Accessor for the default Gradle Version Catalog named "libs".
 * This allows accessing versions and libraries defined in `libs.versions.toml`.
 */
internal val Project.versionCatalog: VersionCatalog
    get() = extensions.getByType<VersionCatalogsExtension>().named("libs")

/**
 * Type-safe accessor for the "configuration" version catalog.
 * Useful for sharing plugin versions or build logic versions across included builds.
 *
 * See workaround: https://github.com/gradle/gradle/issues/15383#issuecomment-779893192
 */
internal val Project.configVersions: VersionAccessors
    get() = the<LibrariesForConfiguration>().versions

/**
 * Type-safe accessor for the default "libs" version catalog generated by Gradle.
 * Provides dot-notation access to libraries (e.g., `libs.androidx.core`).
 */
internal val Project.libs: LibrariesForLibs
    get() = the()

//endregion

//region General Utilities

/**
 * Checks if a plugin with the specified [id] is currently applied to the project.
 *
 * @param id The plugin ID string (e.g., "com.android.application").
 * @return `true` if the plugin is applied, `false` otherwise.
 */
internal fun Project.hasPlugin(id: String) = plugins.hasPlugin(id)

//endregion

//region Kotlin Configuration

/**
 * Configures common Kotlin settings for any project type (JVM, Android, Multiplatform).
 * Applies the [block] to the [KotlinBaseExtension].
 *
 * Use this for settings shared across all targets, such as explicit API mode or general compiler options.
 */
internal fun Project.kotlinCommon(block: KotlinBaseExtension.() -> Unit) =
    extensions.configure("kotlin", block)

/**
 * Configures the Kotlin Multiplatform plugin settings.
 * Applies the [block] to the [KotlinMultiplatformExtension].
 *
 * Use this to define targets (jvm, android, ios), source sets, and KMP-specific compiler options.
 */
internal fun Project.kotlinMultiplatform(block: KotlinMultiplatformExtension.() -> Unit) =
    extensions.configure<KotlinMultiplatformExtension>(block)

/**
 * Configures the Kotlin JVM plugin settings (for pure Java/Kotlin modules).
 * Applies the [block] to the [KotlinJvmExtension].
 */
internal fun Project.kotlinJvm(block: KotlinJvmExtension.() -> Unit) =
    extensions.configure<KotlinJvmExtension>(block)

/**
 * Configures the Kotlin Android plugin settings.
 * Applies the [block] to the [KotlinAndroidExtension].
 *
 * Note: Use this for Kotlin options specific to Android compilation.
 */
internal fun Project.kotlinAndroid(block: KotlinAndroidExtension.() -> Unit) =
    extensions.configure<KotlinAndroidExtension>(block)

//endregion

//region Android DSL (Static Configuration)

/**
 * Configures common Android Gradle Plugin settings shared across all module types
 * (Application, Library, Dynamic Feature, Test).
 *
 * Use this for generic setup like `compileSdk`, `minSdk`, `compileOptions`, etc.
 * The wildcard generics `<*>` allow this method to work with any specific Android extension.
 */
internal fun Project.androidCommon(block: CommonExtension.() -> Unit) =
    extensions.configure("android", block)

/**
 * Configures specific settings for an Android Application module (`com.android.application`).
 * Applies the [block] to the [ApplicationExtension].
 *
 * Use this for `defaultConfig` settings like `targetSdk`, `versionCode`, `versionName`, and `buildTypes`.
 */
internal fun Project.androidApplication(block: ApplicationExtension.() -> Unit) =
    extensions.configure<ApplicationExtension>(block)

/**
 * Configures specific settings for an Android Library module (`com.android.library`).
 * Applies the [block] to the [LibraryExtension].
 *
 * Use this for library-specific settings like `consumerProguardFiles`.
 */
internal fun Project.androidLibrary(block: LibraryExtension.() -> Unit) =
    extensions.configure<LibraryExtension>(block)

/**
 * Configures specific settings for an Android Dynamic Feature module (`com.android.dynamic-feature`).
 * Applies the [block] to the [DynamicFeatureExtension].
 */
internal fun Project.androidDynamicFeature(block: DynamicFeatureExtension.() -> Unit) =
    extensions.configure<DynamicFeatureExtension>(block)

/**
 * Configures specific settings for a separate Android Test module (`com.android.test`).
 * Applies the [block] to the [TestExtension].
 */
internal fun Project.androidTest(block: TestExtension.() -> Unit) =
    extensions.configure<TestExtension>(block)

//endregion

//region Android Variant API (Dynamic Configuration)

/**
 * Configures the Android Variant API components for any Android module.
 *
 * Use this block for `beforeVariants` (variant filtering) or generic `onVariants` logic
 * that doesn't depend on specific artifact types.
 */
internal fun Project.androidCommonComponents(block: AndroidComponentsExtension<*, *, *>.() -> Unit) =
    extensions.configure("androidComponents", block)

/**
 * Configures the Android Variant API specifically for Application modules.
 *
 * Use this to access [ApplicationAndroidComponentsExtension] for modifying application variants,
 * adjusting outputs (APKs), or hooking into the build flow of an app.
 */
internal fun Project.androidApplicationComponents(block: ApplicationAndroidComponentsExtension.() -> Unit) =
    extensions.configure<ApplicationAndroidComponentsExtension>(block)

/**
 * Configures the Android Variant API specifically for Library modules.
 *
 * Use this to access [LibraryAndroidComponentsExtension] for modifying library variants (AARs).
 */
internal fun Project.androidLibraryComponents(block: LibraryAndroidComponentsExtension.() -> Unit) =
    extensions.configure<LibraryAndroidComponentsExtension>(block)

/**
 * Configures the Android Variant API specifically for Test modules.
 */
internal fun Project.androidTestComponents(block: TestAndroidComponentsExtension.() -> Unit) =
    extensions.configure<TestAndroidComponentsExtension>(block)

/**
 * Configures the Android Variant API specifically for Dynamic Feature modules.
 */
internal fun Project.androidDynamicFeatureComponents(block: DynamicFeatureAndroidComponentsExtension.() -> Unit) =
    extensions.configure<DynamicFeatureAndroidComponentsExtension>(block)

/**
 * Configures the Android Variant API specifically for Kotlin Multiplatform projects targeting Android.
 * This is crucial for configuring Android variants within a KMP structure.
 */
internal fun Project.androidKotlinMultiplatformLibraryComponents(block: KotlinMultiplatformAndroidComponentsExtension.() -> Unit) =
    extensions.configure<KotlinMultiplatformAndroidComponentsExtension>(block)

//endregion

//region Dependency Helpers

/**
 * Adds a dependency to the 'implementation' configuration.
 *
 * @param dependencyNotation The dependency notation (e.g., string "group:name:version" or a version catalog reference).
 */
internal fun DependencyHandler.implementation(dependencyNotation: Any) =
    add("implementation", dependencyNotation)

/**
 * Adds a dependency to the 'testImplementation' configuration (Unit tests).
 *
 * @param dependencyNotation The dependency notation.
 */
internal fun DependencyHandler.testImplementation(dependencyNotation: Any) =
    add("testImplementation", dependencyNotation)

/**
 * Adds a dependency to the 'androidTestImplementation' configuration (Instrumented tests).
 *
 * @param dependencyNotation The dependency notation.
 */
internal fun DependencyHandler.androidTestImplementation(dependencyNotation: Any) =
    add("androidTestImplementation", dependencyNotation)

/**
 * Adds a dependency to the 'coreLibraryDesugaring' configuration.
 * Required for using newer Java APIs on older Android devices (API desugaring).
 *
 * @param dependencyNotation The dependency notation (typically `libs.android.desugarJdkLibs`).
 */
internal fun DependencyHandler.coreLibraryDesugaring(dependencyNotation: Any) =
    add("coreLibraryDesugaring", dependencyNotation)

//endregion
